---
title: "エラー処理"
category: 13
tags: 
created_at: 2020-04-01 01:49:46 +0900
updated_at: 2020-04-01 01:49:46 +0900
published: true
number: 33
---

# エラー処理
- Optional\<Wrapped>
- Result<T, Error>
- do-catch
- fatalError
- アサーション

## Optional\<Wrapped>
よく使うやつ、関数の返り値の型をOptional型にして、条件分岐で正常値やらnilやらを返す、利用する側ではoptional bindingとかで処理をわける

## Result\<T, Error>
おもしろいこれ
.successと.failureを返す列挙型Resultをつくる
```swift
enum Result<T, Error : Swift.Error> {
  case success(T)
  case failure(Error)
}
```
次にエラーの詳細を表す列挙型をつくる
```swift
enum DatabaseError : Error {
  case entryNotFound
  case duplicationEntity
  case invalidEntity(reason: String)
}
```
例外が発生するかもしれないメソッドの返り値の型としてResult<T, Error>を指定する
```swift
func findUser(byID id: Int) -> Result<User, DatabaseError> {
  if (なんかの条件) {
    return .success(user)
  }
  return .failure(.entryNotFound)
}

let result = findUser(byID: 1)
switch result {
case let .success(user):
  hoge
case let .failure(error):
  switch error {
  case .entryNotFound:
  case .duplicationEntity:
  case .invalidEntity(let reason):
  }
}
```
case let については3.6節参照

## do-catch
基本
```swift
do {
  throw エラー起きるメソッド
} catch {
  例外処理
}
```
throwsでdo-catchを使わないでthrowできるようになる、try-catchで例外処理をする
```swift
enum OperationError : Error {
  case overCapacity
}

func triple(of: int) throws -> {
  guard int <= Int.max / 3 else {
    throw OperationError.overCapacity
  }
  return int * 3
}

let int = Int.Max

do {
  let tripleOfInt = try triple(of: int)
  成功時処理
} catch {
  例外処理
}
```

## fatalError
エラー発生時終了

## アサーション
debug時のみエラー発生時終了
